spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/crawler
      username: root
      password: 1992!Ding
      driver-class-name: com.mysql.jdbc.Driver
      min-idle: 5
      max-active: 50
      filter:
        slf4j:
          enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

