spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
spring.jpa.properties.hibernate.format_sql: false

